### ISSUE TITLE
GCC support

### ISSUE THREAD

**Issue by sg-** [pyocd/FlashAlgo#6]
Currently GCC linker file doesnt create output that is compatible with armcc tools. The c_blob and py_blobs rely on armcc output formats. For GCC support the following is needed:
1. makefile in pgen extended to support post build user commands
2. *.ld modified to mimic the same memory layout as *.sct
3. possible update to scripts/generate_blobs.py if gcc output and keywords are not the same as armcc.

**Comment by flit** [comment]
Fixed!
