### ISSUE TITLE
Is there a way to READ external flash?

### ISSUE THREAD

**Issue by xray-bit** [pyocd/FlashAlgo#60]
Is there a way to READ external flash?

**Comment by flit** [comment]
The [CMSIS-Pack flash algorithm specification](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/flashAlgorithm.html) (FLM), which this repo implements, does not provide an API to read flash.

However, Segger's [Open Flashloader](https://wiki.segger.com/Open_Flashloader#Function_Overview) (OFL) specification, notionally based on FLM, adds a `SEGGER_OPEN_Read()` API. (Unfortunately, OFL algos are only compatible with the FLM spec at the API level. The OFL algos themselves expect a very different runtime environment, at least when built like the OFL examples.)

The full prototype is this:

```c
int SEGGER_OPEN_Read(U32 Addr, U32 NumBytes, U8 *pDestBuff)
```

There's no reason this API couldn't be added to an algo built with this repo as an extension. I plan on proposing some extensions to the FLM spec; this can be included, probably renamed to just `ReadPage()`.

For pyocd, I assume that the `Init()` API will configure external flash such that it is memory mapped. It has a flag that can be set on flash memory regions telling it that it needs to init the flash algo before attemping to read the flash memory. This works for the very few cases I have to test, although it obviously only supports memory mappable external flash.

**Comment by xray-bit** [comment]
Hi, @flit 

```
int ProgramPage (unsigned long adr, unsigned long sz, unsigned char *buf)
```

How does this function receive `buf` data from SWD? I want to learn this knowledge. Do you know where I can learn this? Can you enlighten me?
I think if we can send data to the buffer of `buf` via SWD, can we also read the data in `buf` from SWD?
(Via Google Translate)

**Comment by flit** [comment]
First of all , the [CMSIS-Pack flash algorithm specification](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/flashAlgorithm.html) is useful documentation.

The general process for programming flash using a CMSIS-Pack algorithm is this:

1. Download flash algorithm code and data (extracted from the. FLM file, which is an ELF file) to RAM on the target device.
2. Write a `bkpt #0` instruction (0xbe00) to RAM, usually prepended to the flash algorithm's code.
2. Invoke the `Init()` entry point, passing the "erase" operation type. Other parameters can be set to 0.
3. Invoke the `EraseSector()` entry point with base address of sector to erase (or use `EraseChip()`). Repeat for all sectors to erase.
4. Invoke the `Init()` entry point, passing the "program" operation type. Same as before, the other parameters can be set to 0.
5. Load data for the page to program to a buffer in target RAM.
6. Invoke the `ProgramPage()` entry point, with `adr` set to flash page base address, `sz` set to size of data to program (typically one page) , and `buf` set to the base address of the buffer to which data was copied. Repeat from step 5  for all pages to program.
7. Invoke the `UnInit()` entry point.

To call an entry point:

1. Ensure `SP` is set to an limit address of a RAM region dedicated to stack, usually a minimum of 256 bytes.
2. Set `LR` to the address of the `bkpt` instruction that was placed in RAM.
3. Set `R9` to the base address where the flash algorithm's data was loaded in RAM.
4. Set `R0` through `R3` to parameters for the entry point.
5. Set `PC` to the entry point address with bit 0 set (e.g., entry point | 1).

The addresses of the entry points are determined from the values in the ELF file's symbol table, offset by the base address of the code loaded to RAM. For instance, if the `ProgramPage` symbol has a value of 0x1d8, and the algorithm code was loaded to 0x20000002 (with the breakpoint at 0x20000000). then the `ProgramPage` entry point address is 0x200001da.

This is all encapsulated in code in the [`pyocd.flash.flash.Flash`](https://github.com/pyocd/pyOCD/blob/main/pyocd/flash/flash.py) class in pyocd. The [`init()`](https://github.com/pyocd/pyOCD/blob/a7b2f00c8450f8af9c08ce66df7faa223e4699f1/pyocd/flash/flash.py#L195) method downloads the flash algorithm and calls the `Init()` API. The [`program_page()`](https://github.com/pyocd/pyOCD/blob/a7b2f00c8450f8af9c08ce66df7faa223e4699f1/pyocd/flash/flash.py#L376) method copies the page data to target RAM and invokes the `ProgramPage()` entry point. The [`_call_function_and_wait()`](https://github.com/pyocd/pyOCD/blob/a7b2f00c8450f8af9c08ce66df7faa223e4699f1/pyocd/flash/flash.py#L630) method runs one of the API entry points to completion, and is used by the other methods..

**Comment by xray-bit** [comment]
thx a lot, @flit!
I will try to customize a function and then try to call it.
